const Log = require('../utils/debug.js');

/**
 * 수업료 목록 조회
 */    
paymentList = (req, res, connection) => { 
    
    let sql = `
    SELECT  A.STUDENT_ID AS "studentId",
            A.STUDENT_NO AS "studentNo",
            A.KOREAN_NAME AS "koreanName",
            A.ENTRANCE_DAY AS "entranceDay",
            A.STUDENT_STATUS AS "studentStatus",
            A.STUDENT_STATUS_NAME AS "studentStatusName",
            A.ADMISSION_FEE AS "admissionFee",
            A.REDUCTION_TYPE AS "reductionType",
            A.REDUCTION_TYPE_NAME AS "reductionTypeName",
            A.SEMESTER_ID AS "semesterId",
            A.SEMESTER_NAME AS "semesterName",
            A.DEPARTMENT AS "department",
            A.DEPARTMENT_NAME AS "departmentName",
            A.CLASS_NAME AS "className",
            A.GRADE AS "grade",
            A.GRADE_NAME AS "gradeName",
            A.CLASS_TYPE AS "classType",
            A.CLASS_NO AS "classNo",
            A.SCHOOLFEE_TYPE AS "schoolfeeType",
            A.SCHOOLFEE_TYPE_NAME AS "schoolfeeTypeName",
            A.CLASS_ID AS "classId",
            A.LAST_CLASS_ID AS "lastClassId",
            A.ABANDON_REASON AS "abandonReason",
            A.ABANDON_REASON_NAME AS "abandonReasonName",
            A.CLASS_START_DATE AS "classStartDate",
            A.CLASS_END_DATE AS "classEndDate",
            
            IFNULL(A.FEE_01,0) AS "fee01",
            IFNULL(A.FEE_02,0) AS "fee02",
            IFNULL(A.FEE_03,0) AS "fee03",
            IFNULL(A.FEE_04,0) AS "fee04",
            IFNULL(A.FEE_05,0) AS "fee05",
            IFNULL(A.FEE_06,0) AS "fee06",
            IFNULL(A.FEE_07,0) AS "fee07",
            IFNULL(A.FEE_08,0) AS "fee08",
            IFNULL(A.FEE_09,0) AS "fee09",
            IFNULL(A.FEE_10,0) AS "fee10",
            IFNULL(A.FEE_11,0) AS "fee11",
            IFNULL(A.FEE_12,0) AS "fee12",

            A.COM01  AS "com01",
            A.COM02  AS "com02",
            A.COM03  AS "com03",
            A.COM04  AS "com04",
            A.COM05  AS "com05",
            A.COM06  AS "com06",
            A.COM07  AS "com07",
            A.COM08  AS "com08",
            A.COM09  AS "com09",
            A.COM10  AS "com10",
            A.COM11  AS "com11",
            A.COM11  AS "com11",
            A.COM12  AS "com12",
    
            CASE WHEN A.FEE_01 IS NULL THEN NULL ELSE A.PAY_01 END AS "pay01",
            CASE WHEN A.FEE_02 IS NULL THEN NULL ELSE A.PAY_02 END AS "pay02",
            CASE WHEN A.FEE_03 IS NULL THEN NULL ELSE A.PAY_03 END AS "pay03",
            CASE WHEN A.FEE_04 IS NULL THEN NULL ELSE A.PAY_04 END AS "pay04",
            CASE WHEN A.FEE_05 IS NULL THEN NULL ELSE A.PAY_05 END AS "pay05",
            CASE WHEN A.FEE_06 IS NULL THEN NULL ELSE A.PAY_06 END AS "pay06",
            CASE WHEN A.FEE_07 IS NULL THEN NULL ELSE A.PAY_07 END AS "pay07",
            CASE WHEN A.FEE_08 IS NULL THEN NULL ELSE A.PAY_08 END AS "pay08",
            CASE WHEN A.FEE_09 IS NULL THEN NULL ELSE A.PAY_09 END AS "pay09",
            CASE WHEN A.FEE_10 IS NULL THEN NULL ELSE A.PAY_10 END AS "pay10",
            CASE WHEN A.FEE_11 IS NULL THEN NULL ELSE A.PAY_11 END AS "pay11",
            CASE WHEN A.FEE_12 IS NULL THEN NULL ELSE A.PAY_12 END AS "pay12",
            '${req.query.applyYear}' AS "applyYear"
    FROM (
      SELECT A.STUDENT_ID,
              A.STUDENT_NO,
              A.KOREAN_NAME,
              A.ENTRANCE_DAY,
              AF.STUDENT_STATUS,
              A.ADMISSION_FEE,
              C1.CODE_NAME AS STUDENT_STATUS_NAME,
              B.REDUCTION_TYPE,
              C2.CODE_NAME AS REDUCTION_TYPE_NAME,
              C.SEMESTER_ID,
              D.SEMESTER_NAME,
              C.DEPARTMENT,
              C4.CODE_NAME AS DEPARTMENT_NAME,
              C.CLASS_TYPE,
              C.CLASS_NAME,
              C.GRADE,
              C5.CODE_NAME AS GRADE_NAME,
              C.CLASS_NO,
              C.SCHOOLFEE_TYPE,
              C3.CODE_NAME AS SCHOOLFEE_TYPE_NAME,
              A.LAST_CLASS_ID,
              C.CLASS_ID,
              BF.INPUT_DATE AS BF_INPUT_DATE,
              AF.INPUT_DATE AS AF_INPUT_DATE,
              IFNULL(B.START_DATE, '') AS CLASS_START_DATE,
              IFNULL(B.END_DATE, '') AS CLASS_END_DATE,
              B.ABANDON_REASON,
              IFNULL(C6.CODE_NAME, '') AS ABANDON_REASON_NAME,

      (SELECT CASE WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'NA' THEN REGULAR_SCHOOL_FEE
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE1
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE2
                   WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'MC' THEN REGULAR_SCHOOL_FEE_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE1_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE2_DISCOUNT
              ELSE 0 END AS FEE
      FROM SCHOOL_FEE X
      WHERE X.APPLY_YEAR = '${req.query.applyYear}'
      AND X.APPLY_MONTH = '01'
      AND X.SEMESTER_ID = C.SEMESTER_ID) AS FEE_01,

      (SELECT CASE WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'NA' THEN REGULAR_SCHOOL_FEE
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE1
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE2
                   WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'MC' THEN REGULAR_SCHOOL_FEE_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE1_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE2_DISCOUNT
              ELSE 0 END AS FEE
      FROM SCHOOL_FEE X
      WHERE X.APPLY_YEAR = '${req.query.applyYear}'
      AND X.APPLY_MONTH = '02'
      AND X.SEMESTER_ID = C.SEMESTER_ID) AS FEE_02,

      (SELECT CASE WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'NA' THEN REGULAR_SCHOOL_FEE
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE1
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE2
                   WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'MC' THEN REGULAR_SCHOOL_FEE_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE1_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE2_DISCOUNT
              ELSE 0 END AS FEE
      FROM SCHOOL_FEE X
      WHERE X.APPLY_YEAR = '${req.query.applyYear}'
      AND X.APPLY_MONTH = '03'
      AND X.SEMESTER_ID = C.SEMESTER_ID) AS FEE_03,

      (SELECT CASE WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'NA' THEN REGULAR_SCHOOL_FEE
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE1
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE2
                   WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'MC' THEN REGULAR_SCHOOL_FEE_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE1_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE2_DISCOUNT
              ELSE 0 END AS FEE
      FROM SCHOOL_FEE X
      WHERE X.APPLY_YEAR = '${req.query.applyYear}'
      AND X.APPLY_MONTH = '04'
      AND X.SEMESTER_ID = C.SEMESTER_ID) AS FEE_04,

      (SELECT CASE WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'NA' THEN REGULAR_SCHOOL_FEE
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE1
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE2
                   WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'MC' THEN REGULAR_SCHOOL_FEE_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE1_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE2_DISCOUNT
              ELSE 0 END AS FEE
      FROM SCHOOL_FEE X
      WHERE X.APPLY_YEAR = '${req.query.applyYear}'
      AND X.APPLY_MONTH = '05'
      AND X.SEMESTER_ID = C.SEMESTER_ID) AS FEE_05,

      (SELECT CASE WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'NA' THEN REGULAR_SCHOOL_FEE
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE1
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE2
                   WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'MC' THEN REGULAR_SCHOOL_FEE_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE1_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE2_DISCOUNT
              ELSE 0 END AS FEE
      FROM SCHOOL_FEE X
      WHERE X.APPLY_YEAR = '${req.query.applyYear}'
      AND X.APPLY_MONTH = '06'
      AND X.SEMESTER_ID = C.SEMESTER_ID) AS FEE_06,

      (SELECT CASE WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'NA' THEN REGULAR_SCHOOL_FEE
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE1
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE2
                   WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'MC' THEN REGULAR_SCHOOL_FEE_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE1_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE2_DISCOUNT
              ELSE 0 END AS FEE
      FROM SCHOOL_FEE X
      WHERE X.APPLY_YEAR = '${req.query.applyYear}'
      AND X.APPLY_MONTH = '07'
      AND X.SEMESTER_ID = C.SEMESTER_ID) AS FEE_07,

      (SELECT CASE WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'NA' THEN REGULAR_SCHOOL_FEE
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE1
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE2
                   WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'MC' THEN REGULAR_SCHOOL_FEE_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE1_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE2_DISCOUNT
              ELSE 0 END AS FEE
      FROM SCHOOL_FEE X
      WHERE X.APPLY_YEAR = '${req.query.applyYear}'
      AND X.APPLY_MONTH = '08'
      AND X.SEMESTER_ID = C.SEMESTER_ID) AS FEE_08,

      (SELECT CASE WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'NA' THEN REGULAR_SCHOOL_FEE
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE1
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE2
                   WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'MC' THEN REGULAR_SCHOOL_FEE_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE1_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE2_DISCOUNT
              ELSE 0 END AS FEE
      FROM SCHOOL_FEE X
      WHERE X.APPLY_YEAR = '${req.query.applyYear}'
      AND X.APPLY_MONTH = '09'
      AND X.SEMESTER_ID = C.SEMESTER_ID) AS FEE_09,

      (SELECT CASE WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'NA' THEN REGULAR_SCHOOL_FEE
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE1
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE2
                   WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'MC' THEN REGULAR_SCHOOL_FEE_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE1_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE2_DISCOUNT
              ELSE 0 END AS FEE
      FROM SCHOOL_FEE X
      WHERE X.APPLY_YEAR = '${req.query.applyYear}'
      AND X.APPLY_MONTH = '10'
      AND X.SEMESTER_ID = C.SEMESTER_ID) AS FEE_10,

      (SELECT CASE WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'NA' THEN REGULAR_SCHOOL_FEE
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE1
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE2
                   WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'MC' THEN REGULAR_SCHOOL_FEE_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE1_DISCOUNT
                   WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE2_DISCOUNT
              ELSE 0 END AS FEE
      FROM SCHOOL_FEE X
      WHERE X.APPLY_YEAR = '${req.query.applyYear}'
      AND X.APPLY_MONTH = '11'
      AND X.SEMESTER_ID = C.SEMESTER_ID) AS FEE_11,

      (SELECT CASE WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'NA' THEN REGULAR_SCHOOL_FEE
                  WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE1
                  WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'NA' THEN EXTRA_SCHOOL_FEE2
                  WHEN C.SCHOOLFEE_TYPE = 'RE' AND B.REDUCTION_TYPE = 'MC' THEN REGULAR_SCHOOL_FEE_DISCOUNT
                  WHEN C.SCHOOLFEE_TYPE = 'E1' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE1_DISCOUNT
                  WHEN C.SCHOOLFEE_TYPE = 'E2' AND B.REDUCTION_TYPE = 'MC' THEN EXTRA_SCHOOL_FEE2_DISCOUNT
              ELSE 0 END AS FEE
      FROM SCHOOL_FEE X
      WHERE X.APPLY_YEAR = '${req.query.applyYear}'
      AND X.APPLY_MONTH = '12'
      AND X.SEMESTER_ID = C.SEMESTER_ID) AS FEE_12,

      (SELECT X.SCHOOL_FEE_STATUS
      FROM PAYMENT X
      WHERE X.PAYMENT_YEAR = '${req.query.applyYear}'
      AND X.PAYMENT_MONTH = '01'
      AND X.STUDENT_ID = A.STUDENT_ID
      AND X.SCHOOL_FEE_TYPE = C.SCHOOLFEE_TYPE) AS PAY_01,

      (SELECT X.SCHOOL_FEE_STATUS
      FROM PAYMENT X
      WHERE X.PAYMENT_YEAR = '${req.query.applyYear}'
      AND X.PAYMENT_MONTH = '02'
      AND X.STUDENT_ID = A.STUDENT_ID
      AND X.SCHOOL_FEE_TYPE = C.SCHOOLFEE_TYPE) AS PAY_02,

      (SELECT X.SCHOOL_FEE_STATUS
      FROM PAYMENT X
      WHERE X.PAYMENT_YEAR = '${req.query.applyYear}'
      AND X.PAYMENT_MONTH = '03'
      AND X.STUDENT_ID = A.STUDENT_ID
      AND X.SCHOOL_FEE_TYPE = C.SCHOOLFEE_TYPE) AS PAY_03,

      (SELECT X.SCHOOL_FEE_STATUS
      FROM PAYMENT X
      WHERE X.PAYMENT_YEAR = '${req.query.applyYear}'
      AND X.PAYMENT_MONTH = '04'
      AND X.STUDENT_ID = A.STUDENT_ID
      AND X.SCHOOL_FEE_TYPE = C.SCHOOLFEE_TYPE) AS PAY_04,

      (SELECT X.SCHOOL_FEE_STATUS
      FROM PAYMENT X
      WHERE X.PAYMENT_YEAR = '${req.query.applyYear}'
      AND X.PAYMENT_MONTH = '05'
      AND X.STUDENT_ID = A.STUDENT_ID
      AND X.SCHOOL_FEE_TYPE = C.SCHOOLFEE_TYPE) AS PAY_05,

      (SELECT X.SCHOOL_FEE_STATUS
      FROM PAYMENT X
      WHERE X.PAYMENT_YEAR = '${req.query.applyYear}'
      AND X.PAYMENT_MONTH = '06'
      AND X.STUDENT_ID = A.STUDENT_ID
      AND X.SCHOOL_FEE_TYPE = C.SCHOOLFEE_TYPE) AS PAY_06,

      (SELECT X.SCHOOL_FEE_STATUS
      FROM PAYMENT X
      WHERE X.PAYMENT_YEAR = '${req.query.applyYear}'
      AND X.PAYMENT_MONTH = '07'
      AND X.STUDENT_ID = A.STUDENT_ID
      AND X.SCHOOL_FEE_TYPE = C.SCHOOLFEE_TYPE) AS PAY_07,

      (SELECT X.SCHOOL_FEE_STATUS
      FROM PAYMENT X
      WHERE X.PAYMENT_YEAR = '${req.query.applyYear}'
      AND X.PAYMENT_MONTH = '08'
      AND X.STUDENT_ID = A.STUDENT_ID
      AND X.SCHOOL_FEE_TYPE = C.SCHOOLFEE_TYPE) AS PAY_08,

      (SELECT X.SCHOOL_FEE_STATUS
      FROM PAYMENT X
      WHERE X.PAYMENT_YEAR = '${req.query.applyYear}'
      AND X.PAYMENT_MONTH = '09'
      AND X.STUDENT_ID = A.STUDENT_ID
      AND X.SCHOOL_FEE_TYPE = C.SCHOOLFEE_TYPE) AS PAY_09,

      (SELECT X.SCHOOL_FEE_STATUS
      FROM PAYMENT X
      WHERE X.PAYMENT_YEAR = '${req.query.applyYear}'
      AND X.PAYMENT_MONTH = '10'
      AND X.STUDENT_ID = A.STUDENT_ID
      AND X.SCHOOL_FEE_TYPE = C.SCHOOLFEE_TYPE) AS PAY_10,

      (SELECT X.SCHOOL_FEE_STATUS
      FROM PAYMENT X
      WHERE X.PAYMENT_YEAR = '${req.query.applyYear}'
      AND X.PAYMENT_MONTH = '11'
      AND X.STUDENT_ID = A.STUDENT_ID
      AND X.SCHOOL_FEE_TYPE = C.SCHOOLFEE_TYPE) AS PAY_11,

      (SELECT X.SCHOOL_FEE_STATUS
      FROM PAYMENT X
      WHERE X.PAYMENT_YEAR = '${req.query.applyYear}'
      AND X.PAYMENT_MONTH = '12'
      AND X.STUDENT_ID = A.STUDENT_ID
      AND X.SCHOOL_FEE_TYPE = C.SCHOOLFEE_TYPE) AS PAY_12,

      ## com start ############################
      
     
     CASE WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','01','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE)
               THEN 'T1' 
        WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','01','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE)
               THEN 'T2' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','01','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T3' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','01','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T4'
          ELSE 'F' 
    END AS COM01,
     
     CASE WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','02','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE) 
               THEN 'T1' 
        WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','02','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE)
               THEN 'T2' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','02','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T3' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','02','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T4'
          ELSE 'F' 
    END AS COM02,
     
     CASE WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','03','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE) 
               THEN 'T1' 
        WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','03','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE)
               THEN 'T2' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','03','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T3' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','03','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T4'
          ELSE 'F' 
    END AS COM03,
     
     CASE WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','04','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE) 
               THEN 'T1'  
        WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','04','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE)
               THEN 'T2' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','04','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T3' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','04','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T4'
          ELSE 'F' 
    END AS COM04,
     
     CASE WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','05','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE) 
               THEN 'T1' 
        WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','05','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE)
               THEN 'T2' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','05','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T3' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','05','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T4'
          ELSE 'F' 
    END AS COM05,
     
     CASE WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','06','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE) 
               THEN 'T1' 
        WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','06','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE)
               THEN 'T2' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','06','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T3' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','06','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T4'
          ELSE 'F' 
    END AS COM06,
     
     CASE WHEN B.ABANDON_REASON IS NULL  AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','07','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE)
               THEN 'T1' 
        WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','07','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE)
               THEN 'T2' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','07','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T3' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','07','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T4'
          ELSE 'F' 
    END AS COM07,
    
     CASE WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','08','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE) 
               THEN 'T1' 
        WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','08','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE)
               THEN 'T2' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','08','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T3' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','08','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T4'
          ELSE 'F' 
    END AS COM08,
    
     CASE WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','09','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE) 
               THEN 'T1'  
        WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','09','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE)
               THEN 'T2' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','09','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T3' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','09','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T4'
          ELSE 'F' 
    END AS COM09,
    
     CASE WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','10','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE) 
               THEN 'T1' 
        WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','10','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE)
               THEN 'T2' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','10','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T3' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','10','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T4'
          ELSE 'F' 
    END AS COM10,
    
     CASE WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','11','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE) 
               THEN 'T1' 
        WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','11','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE)
               THEN 'T2' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','11','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T3' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','11','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T4'
          ELSE 'F' 
    END AS COM11,
    
     CASE WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','12','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE) 
               THEN 'T1' 
        WHEN B.ABANDON_REASON IS NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','12','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(D.RECEIPT_END_DATE AS DATE)
               THEN 'T2' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE = B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','12','01') AS DATE)) BETWEEN CAST(D.RECEIPT_START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T3' 
       WHEN B.ABANDON_REASON IS NOT NULL AND
               D.START_DATE != B.START_DATE AND
               LAST_DAY(CAST(CONCAT('${req.query.applyYear}','12','01') AS DATE)) BETWEEN CAST(B.START_DATE AS DATE) AND CAST(B.END_DATE AS DATE)
          THEN 'T4'
          ELSE 'F' 
    END AS COM12
    
  FROM STUDENT_BASIC_INFO A
  LEFT OUTER JOIN CLASSINFO_STUDENTS B ON A.STUDENT_ID = B.STUDENT_ID
  LEFT OUTER JOIN CLASS_INFO C ON B.CLASS_ID = C.CLASS_ID
  LEFT OUTER JOIN SEMESTER D ON D.SEMESTER_ID = C.SEMESTER_ID
  LEFT OUTER JOIN TEACHER E ON C.TEACHER_ID = E.TEACHER_ID
  LEFT OUTER JOIN STUDENT_HISTORY AF ON A.STUDENT_ID = AF.STUDENT_ID AND A.LAST_HISTORY_SEQ = AF.HISTORY_SEQ
  LEFT OUTER JOIN STUDENT_HISTORY BF ON A.STUDENT_ID = BF.STUDENT_ID AND A.LAST_HISTORY_SEQ = BF.HISTORY_SEQ + 1

  LEFT OUTER JOIN COMMON_CODE C1 ON C1.SUPER_CODE = 'STUDENT_STATUS' AND C1.CODE = AF.STUDENT_STATUS
  LEFT OUTER JOIN COMMON_CODE C2 ON C2.SUPER_CODE = 'REDUCTION_TYPE' AND C2.CODE = B.REDUCTION_TYPE
  LEFT OUTER JOIN COMMON_CODE C3 ON C3.SUPER_CODE = 'SCHOOLFEE_TYPE' AND C3.CODE = C.SCHOOLFEE_TYPE
  LEFT OUTER JOIN COMMON_CODE C4 ON C4.SUPER_CODE = 'DEPARTMENT' AND C4.CODE = C.DEPARTMENT
  LEFT OUTER JOIN COMMON_CODE C5 ON C5.SUPER_CODE = 'GRADE' AND C5.CODE = C.GRADE
  LEFT OUTER JOIN COMMON_CODE C6 ON C6.SUPER_CODE = 'ABANDON_REASON' AND C6.CODE = B.ABANDON_REASON

  WHERE 1=1
    `;

    if(!!req.query.teacherId) {
    sql += "\n" + `AND C.TEACHER_ID = '${req.query.teacherId}'`; 
    }
    if(!!req.query.studentNo) {
    sql += "\n" + `AND A.STUDENT_NO = '${req.query.studentNo}'`; 
    }
    if(!!req.query.grade) {
    sql += "\n" + `AND C.GRADE = '${req.query.grade}'`; 
    }
    if(!!req.query.studentName) {
    sql += "\n" + `AND A.KOREAN_NAME LIKE '${req.query.studentName}%'`; 
    }
    if(!!req.query.classNo) {
    sql += "\n" + `AND C.CLASS_NO = '${req.query.classNo}'`; 
    }
    if(!!req.query.department) {
    sql += "\n" + `AND C.DEPARTMENT = '${req.query.department}'`; 
    }
    if(!!req.query.semesterId) {
    sql += "\n" + `AND C.SEMESTER_ID = '${req.query.semesterId}'`; 
    }
    if(!!req.query.schoolFeeType) {
    sql += "\n" + `AND C.SCHOOLFEE_TYPE = '${req.query.schoolFeeType}'`; 
    }
    if(!!req.query.studentStatus) {
    sql += "\n" + `AND AF.STUDENT_STATUS = '${req.query.studentStatus}'`; 
    }

    sql += ` 
    ) A
    ORDER BY A.KOREAN_NAME, A.SEMESTER_ID, A.CLASS_TYPE DESC
    `;    


    connection.query(sql,
        (err, rows, fields) => {
                if(err){
                        Log.error(`/api/payment/list failed. sql=${sql}, error=${err}`);
                        res.send({"payments": []});
                }else{          
                        let payments = [];
                        for(let i=0; i < rows.length; i++){
                                payments.push(rows[i]);
                        }
                        Log.print(`/api/payment/list called  sql=${sql}`);
                        res.send({"payments": payments});
                }
        }
    );
}//schoolfeeList

module.exports = {
    paymentList
}